version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - checkout
      - aws-s3/sync:
          from: .
          to: 's3://joelfreeman.xyz'
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          arguments: |
            --acl public read \
            --cache-control "max-age=86400"
