version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.72
    steps:
      - checkout
      - run: make _build
      - save_cache:
          key: v1-{{ .Environment.CIRCLE_SHA1 }}
          paths: 
            - blog/public
            - blog/themes
  test: 
    docker:
      - image: cibuilds/hugo:0.72
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ .Environment.CIRCLE_SHA1 }}
      - run: make _test
        
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build