version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - checkout
      - run: pip install awscli --user
      - run: aws configure set aws_access_key_id $ACCESS_KEY
      - run: aws configure set aws_secret_access_key $SECRET_KEY 
      - run: aws s3 sync . s3://joelfreeman.xyz
